theme: jekyll-theme-minimal
markdown: kramdown
title: Ben Augenbraun
description: I am currently a PhD student at Harvard University studying ultracold molecules.
logo: /assets/img/ben-beambox.jpg
email: augenbraun@g.harvard.edu
